// Generated by https://quicktype.io

export interface AccountInterface {
  username: string;
  fullname: string;
  email:    string;
}

export interface MessageResponse {
  message: string;
}

export interface LoginInterface {
  username: string;
  password: string;
}

export interface RegisterInterface {
  username: string;
  password: string;
  fullname: string;
  email:    string;
}