// Generated by https://quicktype.io

export interface BookInterface {
  _id:           string;
  id:            number;
  name:          string;
  author:        string[];
  illustrator:   string[];
  description:   string;
  publisher:     string;
  genres:        string[];
  publishedAt:   string;
  weight:        number;
  images:        string[];
  quantity?:     number;
  status:        string;
  __v:           number;
  category?:     string;
  types:         Type[];
}

export interface Type {
  _id:    string;
  name:   string;
  nameTH: string;
  price:  number;
}
