//   "_id": "623832c08f0f31a58698f3af",// Generated by https://quicktype.io

export interface CartInterface {
  _id:        string;
  cartItems:  CartItem[];
  totalItem:  number;
  totalPrice: number;
  createdBy:  AtedBy;
  updatedBy:  AtedBy;
  createdAt:  string;
  updatedAt:  string;
  __v:        number;
}

export interface CartItem {
  id:          number;
  name:        string;
  author:      string[];
  illustrator: string[];
  description: string;
  publisher:   string;
  genres:      string[];
  publishedAt: string;
  weight:      number;
  images:      string[];
  quantity:    number;
  type:        Type;
  totalPrice:  number;
  status:      string;
}

export interface Type {
  name:   string;
  nameTH: string;
  price:  number;
  _id:    string;
}

export interface AtedBy {
  name: string;
  _id:  string;
}

export interface CartItemBySeller {
  seller:      string;
  items:       Item[];
  description: string;
  totalPrice:  number;
  quantity:    number;
}

export interface Item {
  id:          number;
  name:        string;
  author:      string[];
  illustrator: string[];
  description: string;
  publisher:   string;
  genres:      string[];
  publishedAt: string;
  weight:      number;
  images:      string[];
  quantity:    number;
  type:        Type;
  totalPrice:  number;
  status:      string;
}

