// Generated by https://quicktype.io

export interface OrderInterface {
  _id:           string;
  orders:        Order[];
  totalPrice:    number;
  totalItem:     number;
  paymentStatus: string;
  createdBy:     AtedBy;
  updatedBy:     AtedBy;
  createdAt:     string;
  updatedAt:     string;
  __v:           number;
}

export interface AtedBy {
  name: string;
  _id:  string;
}

export interface OrdersCreateInterface {
  orders:     Order[];
  totalPrice: number;
  totalItem:  number;
}

export interface Order {
  seller:      string;
  items:       Item[];
  description: string;
  shipment:    null;
  totalPrice:  number;
  quantity:    number;
  _id:         string;
}

export interface Item {
  id:          number;
  name:        string;
  author:      string[];
  illustrator: string[];
  description: string;
  publisher:   string;
  genres:      string[];
  publishedAt: string;
  weight:      number;
  images:      string[];
  quantity:    number;
  type:        Type;
  totalPrice:  number;
  status:      string;
  _id:         string;
}

export interface Type {
  name:   string;
  nameTH: string;
  price:  number;
  _id:    string;
}
